security:
    encoders:
        App\Entity\User:
            algorithm: sha512
            iterations: 10

    providers:
        User_nick:
            entity: 
                class: App\Entity\User
                property: username

    firewalls:
        frontend:
            anonymous: ~
            provider: User_nick
            form_login: 
                default_target_path: /cloud/accessControl
                always_use_default_target_path: true
                login_path: /cloud/login
                check_path: /cloud/login_check
                csrf_parameter: _csrf_token
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: adspace_logout
                target: /cloud/login

    access_control:
            - { path: ^/cloud/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/cloud/management/*, roles: [ROLE_SUPER_ADMIN]}
            - { path: ^/cloud/accessControl, roles: [ROLE_SUPER_ADMIN, ROLE_ADMINISTRATOR, ROLE_LICENSE_MANAGER, ROLE_REPORT_VIEWER]}
            - { path: ^/cloud/dashboard, roles: [ROLE_SUPER_ADMIN, ROLE_ADMINISTRATOR, ROLE_LICENSE_MANAGER, ROLE_REPORT_VIEWER]}
            - { path: ^/account/*, roles: [ROLE_SUPER_ADMIN, ROLE_ADMINISTRATOR, ROLE_LICENSE_MANAGER] }
            - { path: ^/accountlicense/*, roles: [ROLE_SUPER_ADMIN, ROLE_ADMINISTRATOR, ROLE_LICENSE_MANAGER] }
            - { path: ^/reports/*, roles: [ROLE_SUPER_ADMIN, ROLE_ADMINISTRATOR, ROLE_LICENSE_MANAGER, ROLE_REPORT_VIEWER] }
            - { path: ^/reseller/*, roles: [ROLE_SUPER_ADMIN, ROLE_ADMINISTRATOR] }
